// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresSqlSample.Model;

#nullable disable

namespace PostgresSqlSample.Migrations
{
    [DbContext(typeof(OpenDbContext))]
    partial class OpenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresSqlSample.Model.Test1", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<decimal>("DecimalTest")
                        .HasColumnType("numeric")
                        .HasColumnName("decimal_test");

                    b.Property<double>("DoubleTest")
                        .HasColumnType("double precision")
                        .HasColumnName("double_test");

                    b.Property<float>("FloatTest")
                        .HasColumnType("real")
                        .HasColumnName("float_test");

                    b.Property<long>("LongTest")
                        .HasColumnType("bigint")
                        .HasColumnName("long_test");

                    b.HasKey("Id")
                        .HasName("pk_test1");

                    b.ToTable("test1", "azrng");
                });

            modelBuilder.Entity("PostgresSqlSample.Model.Test2", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_time")
                        .HasComment("创建时间");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("creater")
                        .HasComment("创建人");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modify_time")
                        .HasComment("最后修改时间");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("modifyer")
                        .HasComment("最后修改人");

                    b.HasKey("Id")
                        .HasName("pk_test2");

                    b.ToTable("test2", "azrng");
                });

            modelBuilder.Entity("PostgresSqlSample.Model.Test3", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_time")
                        .HasComment("创建时间");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("creater")
                        .HasComment("创建人");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted")
                        .HasComment("是否删除");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled")
                        .HasComment("是否禁用");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modify_time")
                        .HasComment("最后修改时间");

                    b.Property<string>("Updater")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("modifyer")
                        .HasComment("最后修改人");

                    b.HasKey("Id")
                        .HasName("pk_test3");

                    b.ToTable("test3", "azrng");
                });

            modelBuilder.Entity("PostgresSqlSample.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("主键");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account")
                        .HasComment("账号");

                    b.Property<DateTime>("CreateTime")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasComment("创建时间");

                    b.Property<bool>("IsValid")
                        .HasMaxLength(50)
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid")
                        .HasComment("是否有效");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password")
                        .HasComment("密码");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "azrng");
                });

            modelBuilder.Entity("PostgresSqlSample.Model.UserAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("主键");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address")
                        .HasComment("地址");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("名称");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("用户Id");

                    b.HasKey("Id")
                        .HasName("pk_useraddress");

                    b.ToTable("useraddress", "azrng");
                });
#pragma warning restore 612, 618
        }
    }
}
