-- ============================================
-- Common.Dapper 单元测试数据库准备脚本
-- 数据库类型: PostgreSQL
-- ============================================

-- 1. 创建 Schema（如果不存在）
CREATE SCHEMA IF NOT EXISTS example;

-- 2. 创建用户表
CREATE TABLE IF NOT EXISTS example."user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_user PRIMARY KEY,
    account     VARCHAR(50)                               NOT NULL,
    pass_word   VARCHAR(50)                               NOT NULL,
    name        TEXT                                      NOT NULL,
    sex         INTEGER                                   NOT NULL,
    credit      DOUBLE PRECISION                          NOT NULL,
    group_id    BIGINT                                    NOT NULL,
    creater     VARCHAR(50) DEFAULT ''::CHARACTER VARYING NOT NULL,
    create_time TIMESTAMP                                 NOT NULL,
    modifyer    VARCHAR(50) DEFAULT ''::CHARACTER VARYING NOT NULL,
    modify_time TIMESTAMP                                 NOT NULL,
    deleted     BOOLEAN                                   NOT NULL,
    disabled    BOOLEAN                                   NOT NULL
);

-- 3. 创建索引（提升查询性能）
CREATE INDEX IF NOT EXISTS idx_user_account ON example."user"(account);
CREATE INDEX IF NOT EXISTS idx_user_deleted ON example."user"(deleted);
CREATE INDEX IF NOT EXISTS idx_user_group_id ON example."user"(group_id);

-- 4. 插入测试数据
INSERT INTO example."user"
    (account, pass_word, name, sex, credit, group_id, creater, create_time, modifyer, modify_time, deleted, disabled)
VALUES
    ('admin', 'admin123', '系统管理员', 1, 1000.0, 1, 'system', NOW(), 'system', NOW(), false, false),
    ('user001', 'pass123', '测试用户1', 1, 100.0, 1, 'system', NOW(), 'system', NOW(), false, false),
    ('user002', 'pass123', '测试用户2', 0, 200.0, 2, 'system', NOW(), 'system', NOW(), false, false),
    ('user003', 'pass123', '测试用户3', 1, 150.0, 1, 'system', NOW(), 'system', NOW(), false, false),
    ('user004', 'pass123', '测试用户4', 0, 300.0, 2, 'system', NOW(), 'system', NOW(), false, false),
    ('deleted_user', 'pass123', '已删除用户', 1, 50.0, 1, 'system', NOW(), 'system', NOW(), true, false)
ON CONFLICT DO NOTHING;

-- 5. 查询验证
SELECT 'User表记录数: ' || COUNT(*) AS info FROM example."user";
SELECT '未删除的用户数: ' || COUNT(*) AS info FROM example."user" WHERE deleted = false;

-- ============================================
-- 使用说明
-- ============================================
-- 1. 执行本脚本前，请确保已创建数据库：
--    CREATE DATABASE test;
--
-- 2. 连接到数据库后执行：
--    psql -U postgres -d test -f DatabaseSetup.sql
--
-- 3. 清理测试数据（可选）：
--    DELETE FROM example."user" WHERE account LIKE 'test%' OR account LIKE 'batch%' OR account LIKE 'trans%';
--
-- 4. 完全清理（删除表和Schema）：
--    DROP TABLE IF EXISTS example."user";
--    DROP SCHEMA IF EXISTS example;
-- ============================================
