using Azrng.Dapper.Repository;

namespace Azrng.Dapper.Test;

public class UnitTest
{
    private readonly IDapperRepository _dapperRepository;

    public UnitTest(IDapperRepository dapperRepository)
    {
        _dapperRepository = dapperRepository;
    }

    /*
     *
     *  表结构定义sql
     *   create table example."user"
(
    id          bigint generated by default as identity
        constraint pk_user
            primary key,
    account     varchar(20)                               not null,
    pass_word   varchar(20)                               not null,
    name        text                                      not null,
    sex         integer                                   not null,
    credit      double precision                          not null,
    group_id    bigint                                    not null,
    creater     varchar(50) default ''::character varying not null,
    create_time timestamp                                 not null,
    modifyer    varchar(50) default ''::character varying not null,
    modify_time timestamp                                 not null,
    deleted     boolean                                   not null,
    disabled    boolean                                   not null
);

     *
     */

    [Fact]
    public async Task TestInsertUser()
    {
        // Arrange
        var user = new User
                   {
                       Account = "testuser",
                       PassWord = "password123",
                       Name = "Test User",
                       Sex = 1,
                       Credit = 100.0,
                       GroupId = 1,
                       Creater = "system",
                       CreateTime = DateTime.Now,
                       Modifyer = "system",
                       ModifyTime = DateTime.Now,
                       Deleted = false,
                       Disabled = false
                   };

        var sql = @"
            INSERT INTO example.""user""
            (account, pass_word, name, sex, credit, group_id, creater, create_time, modifyer, modify_time, deleted, disabled)
            VALUES
            (@Account, @PassWord, @Name, @Sex, @Credit, @GroupId, @Creater, @CreateTime, @Modifyer, @ModifyTime, @Deleted, @Disabled)";

        // Act
        var result = await _dapperRepository.ExecuteAsync(sql, user);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task TestQueryUsers()
    {
        // Arrange
        var sql =
            @"SELECT id, account, pass_word, name, sex, credit, group_id, creater, create_time, modifyer, modify_time, deleted, disabled
                    FROM example.""user"" WHERE deleted = false";

        // Act
        var users = await _dapperRepository.QueryAsync<User>(sql);

        // Assert
        Assert.NotNull(users);
    }

    [Fact]
    public async Task TestQueryUserById()
    {
        // Arrange
        var userId = 1L; // 假设存在ID为1的用户
        var sql =
            @"SELECT id, account, pass_word, name, sex, credit, group_id, creater, create_time, modifyer, modify_time, deleted, disabled
                    FROM example.""user"" WHERE id = @userId AND deleted = false";

        // Act
        await _dapperRepository.QueryFirstOrDefaultAsync<User>(sql, new { userId });
    }

    [Fact]
    public async Task TestUpdateUser()
    {
        // Arrange
        var userId = 1L;
        var sql = @"UPDATE example.""user"" SET name = @name, modifyer = @modifyer, modify_time = @modifyTime
                    WHERE id = @id AND deleted = false";

        // Act
        var result = await _dapperRepository.ExecuteAsync(sql,
            new { id = userId, name = "Updated Name", modifyer = "test", modifyTime = DateTime.Now });

        // Assert
        Assert.True(result >= 0); // 可能更新了0行或更多行
    }

    [Fact]
    public async Task TestDeleteUser()
    {
        // Arrange
        var userId = 1L;
        var sql = @"UPDATE example.""user"" SET deleted = true
                    WHERE id = @id";

        // Act
        var result = await _dapperRepository.ExecuteAsync(sql, new { id = userId });

        // Assert
        Assert.True(result >= 0);
    }
}