using Azrng.DbOperator;
using Xunit.Abstractions;

namespace Common.DbSystemOperator.MySql.Test
{
    /// <summary>
    /// 帮助类
    /// </summary>
    public class MySQLHelperTest
    {
        private readonly IDbHelper _dbHelper;
        private readonly ITestOutputHelper _testOutputHelper;

        public MySQLHelperTest(IDbHelper dbHelper, ITestOutputHelper testOutputHelper)
        {
            _dbHelper = dbHelper;
            _testOutputHelper = testOutputHelper;

            var initSql = @"create table if not exists sample.user_info
                            (
                                id      bigint generated by default as identity primary key,
                                account varchar(20) not null,
                                name    varchar(20) not null
                            );
                            insert into sample.user_info(account, name) values('admin','张三');";
            dbHelper.ExecuteAsync(initSql).GetAwaiter().GetResult();
        }

        /// <summary>
        /// 获取连接字符串
        /// </summary>
        [Fact]
        public void GetConnectionString()
        {
            var result = _dbHelper.ConnectionString;
            Assert.NotNull(result);
            Assert.NotEmpty(result);
        }

        [Fact]
        public async Task ConnectionTest_ReturnOk()
        {
            var result = await _dbHelper.ConnectionTestAsync();
            Assert.True(result);
        }

        [Fact]
        public async Task QueryFirst_ReturnOk()
        {
            var sql = "select account from sample.user_info order by id desc ";
            var result = await _dbHelper.QueryFirstAsync<string>(sql);
            Assert.Equal("admin", result);
        }

        [Fact]
        public async Task ExecuteScalar_ReturnOk()
        {
            var sql = "select account from sample.user_info order by id desc ;";
            var result = await _dbHelper.QueryScalarAsync<string>(sql);
            Assert.Equal("admin", result);
        }

        /// <summary>
        /// 执行sql返回受影响行数
        /// </summary>
        [Fact]
        public async Task Execute_ReturnAffectedRows()
        {
            var sql = $"insert into sample.user_info(account, name) values('{Guid.NewGuid().ToString().Substring(0, 10)}','张三');";

            var result = await _dbHelper.ExecuteAsync(sql);
            Assert.Equal(1, result);
        }

        /// <summary>
        /// 获取总条数
        /// </summary>
        [Fact]
        public async Task GetDataCount_ReturnOk()
        {
            var sql = "select count(1) from sample.user_info ";

            var result = await _dbHelper.GetDataCountAsync(sql);
            Assert.True(result >= 1);
        }

        /// <summary>
        /// 获取总条数
        /// </summary>
        [Fact]
        public async Task GetSplitPageData_ReturnOk()
        {
            var sql = "select account from sample.user_info ";

            var result = await _dbHelper.GetSplitPageDataAsync<string>(sql, 1, 10);
            Assert.True(result.Any());
        }

        /// <summary>
        /// 获取总条数
        /// </summary>
        [Fact]
        public void BuildSplitPageSql_ReturnOk()
        {
            var sql = "select account from sample.user_info ";

            var result = _dbHelper.BuildSplitPageSql(sql, 1, 10);
            Assert.NotNull(result);
            _testOutputHelper.WriteLine(result);
        }
    }
}