namespace Azrng.JSqlParser.Statement.Alter;

/// <summary>
/// Enumerates the types of ALTER operations supported by JSqlParser.
/// </summary>
public enum AlterOperation
{
    Add,
    Alter,
    Drop,
    DropPrimaryKey,
    DropUnique,
    DropForeignKey,
    Modify,
    Change,
    Convert,
    Collate,
    Algorithm,
    Rename,
    RenameTable,
    RenameIndex,
    RenameKey,
    RenameConstraint,
    Comment,
    CommentWithEqualSign,
    Unspecific,
    AddPartition,
    DropPartition,
    DiscardPartition,
    ImportPartition,
    TruncatePartition,
    CoalescePartition,
    ReorganizePartition,
    ExchangePartition,
    AnalyzePartition,
    CheckPartition,
    OptimizePartition,
    RebuildPartition,
    RepairPartition,
    RemovePartitioning,
    PartitionBy,
    SetTableOption,
    Engine,
    Force,
    KeyBlockSize,
    Lock,
    DiscardTablespace,
    ImportTablespace,
    DisableKeys,
    EnableKeys,
    EnableRowLevelSecurity,
    DisableRowLevelSecurity,
    ForceRowLevelSecurity,
    NoForceRowLevelSecurity
}
