using Dapper;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Data;

namespace Azrng.SqlMigration.Service
{
    public class PgSqlDbVersionService : IDbVersionService
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly ILogger<PgSqlDbVersionService> _logger;

        public PgSqlDbVersionService(IServiceProvider serviceProvider,
            ILogger<PgSqlDbVersionService> logger)
        {
            _serviceProvider = serviceProvider;
            _logger = logger;
        }

        public async Task<string> GetCurrentVersionAsync(string migrationName)
        {
            var conn = _serviceProvider.GetRequiredKeyedService<IDbConnection>(migrationName);
            var optionsSnapshot = _serviceProvider.GetRequiredService<IOptionsSnapshot<SqlMigrationOption>>();
            var config = optionsSnapshot.Get(migrationName);
            try
            {
                var querySql = $@"SELECT count(1)
                                FROM pg_class a
                                LEFT OUTER JOIN pg_description b ON b.objsubid = 0 AND a.oid = b.objoid
                                WHERE a.relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = '{config.Schema}')
                                AND a.relkind = 'r' and a.relname='app_version_log';";

                if (await conn.ExecuteScalarAsync<int>(querySql) == 0)
                    return SqlMigrationConst.FirstVersionStr;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"{migrationName} SQL迁移脚本-查询数据库是否存在异常");
                throw;
            }

            var sql =
                $"select version from {config.Schema}.app_version_log order by id desc limit 1";
            var ret = await conn.ExecuteScalarAsync(sql);
            return ret?.ToString() ?? SqlMigrationConst.FirstVersionStr;
        }

        public Task WriteVersionLogAsync(string migrationName, string version)
        {
            var optionsSnapshot = _serviceProvider.GetRequiredService<IOptionsSnapshot<SqlMigrationOption>>();
            var config = optionsSnapshot.Get(migrationName);

            var initSql = @$"CREATE TABLE if not exists {config.Schema}.app_version_log (
                                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                                    version text NOT NULL,
                                    created_time timestamp without time zone NOT NULL,
                                    CONSTRAINT pk_app_version_log PRIMARY KEY (id)
                                );
                                CREATE UNIQUE INDEX if not exists ix_app_version_log_version ON {config.Schema}.app_version_log (version);";

            var writeSql =
                $"insert into {config.Schema}.app_version_log(version,created_time) values(@version,@time);";
            var param = new
            {
                version, time = DateTime.SpecifyKind(DateTime.UtcNow, DateTimeKind.Unspecified).AddHours(8)
            };
            var conn = _serviceProvider.GetRequiredKeyedService<IDbConnection>(migrationName);
            return conn.ExecuteAsync($"{initSql}{writeSql}", param);
        }
    }
}